#!/bin/bash

THIS_DIR=$(cd $(dirname $0); pwd)
cd $THIS_DIR

install() {
	    cd libs
		sudo cp /usr/share/zoneinfo/Asia/Tehran /etc/localtime
		sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
		sudo apt-get install g++-4.7 -y c++-4.7 -y
		sudo apt-get update
		sudo apt-get upgrade
		sudo apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y
		sudo apt-get install screen -y
		sudo apt-get install tmux -y
		sudo apt-get install libstdc++6 -y
		sudo apt-get install lua-lgi -y
		sudo apt-get install libnotify-dev -y
		sudo apt-get update
		sudo apt-get upgrade
		sudo apt-get install lua5.1 luarocks lua-socket lua-sec redis-server curl 
		sudo luarocks install oauth 
		sudo luarocks install redis-lua 
		sudo luarocks install lua-cjson 
		sudo luarocks install ansicolors 
		sudo apt-get install libstdc++9
		sudo apt-get install libconfig++9v5 libstdc++6
		sudo luarocks install serpent 
		sudo apt install speedtest-cli
		sudo wget https://valtman.name/files/telegram-bot-180116-nightly-linux
		sudo mv telegram-bot-180116-nightly-linux tdbot
		sudo chmod +x tdbot
		cd ..
}

logo_play() {
    declare -A txtlogo
    seconds="0.010"
    txtlogo[1]="        :::   :::           :::    :::::::::::           :::        :::::::::       ::::::::       ::::::::: "
	txtlogo[2]="      :+:+: :+:+:        :+: :+:      :+:             :+: :+:      :+:    :+:     :+:    :+:      :+:    :+: "
	txtlogo[3]="    +:+ +:+:+ +:+      +:+   +:+     +:+            +:+   +:+     +:+    +:+     +:+    +:+      +:+    +:+  "
	txtlogo[4]="   +#+  +:+  +#+     +#++:++#++:    +#+           +#++:++#++:    +#+    +:+     +#+    +:+      +#++:++#:    "
	txtlogo[5]="  +#+       +#+     +#+     +#+    +#+           +#+     +#+    +#+    +#+     +#+    +#+      +#+    +#+    "
	txtlogo[6]=" #+#       #+#     #+#     #+#    #+#           #+#     #+#    #+#    #+#     #+#    #+#      #+#    #+#     "
	txtlogo[7]="###       ###     ###     ###    ###           ###     ###    #########       ########       ###    ###      " 
    printf "\033[38;5;600m\t"
    for i in ${!txtlogo[@]}; do
        for x in `seq 0 ${#txtlogo[$i]}`; do
            printf "${txtlogo[$i]:$x:1}"
            sleep $seconds
        done
        printf "\n\t"
    done
    printf "\n"
	echo -e "\e[0m"
}
deltgbot() {
 rm -rf $HOME/.telegram-bot
}
 config() {
mkdir $HOME/.telegram-bot; cat <<EOF > $HOME/.telegram-bot/config
default_profile = "cli";
cli = {
lua_script = "$HOME/MaTaDoR/bot/Bot.lua";
};
EOF
printf "\nConfig Has Been Saved.\n"
}
clilaunch() {
./libs/tdbot | grep -v "{"
}

clilaunchauto() {
while true; do
./libs/tdbot | grep -v "{"
done
}

apilaunch() {
lua ./bot/Api.lua
}

apilaunchauto() {
while true; do
lua ./bot/Api.lua
done
}

Runcli() {
./libs/tdbot -p cli --login --phone=${1}
} 

Runapi() {
./libs/tdbot -p cli --login --bot=${1}
}

case $1 in
config)
logo_play
printf "Please wait...\n"
config ${2}
exit ;;

logcli)
logo_play
echo "Please Insert Your Phone Number..."
read phone_number
Runcli ${phone_number}
echo 'Your Cli Bot Loged In Successfully.'
exit;;

logapi)
logo_play
echo "Please Insert Your Bot Token..."
read Bot_Token
Runapi ${Bot_Token}
echo 'Your Api Bot Loged In Successfully.'
exit;;

install)
logo_play
install
exit;;

cli)
printf "New MaTaDoR-Cli is Launching...\n"
logo_play
clilaunch
exit;;

autocli)
logo_play
clilaunchauto
printf "New MaTaDoR-Cli is Auto Launching..."
exit;;

api)
printf "New MaTaDoR-Api is Launching...\n"
logo_play
apilaunch
exit;;

autoapi)
logo_play
apilaunchauto
printf "New MaTaDoR-Api is Auto Launching..."
exit;;

reset)
logo_play
printf "Please wait for delete telegram-bot...\n"
deltgbot
sleep 1
echo '.telegram-bot Deleted Successfully.'
exit;;

esac

exit 0
 
